"""Public and compatibility export lists for ``polyfempy.differentiable``."""

from __future__ import annotations


PUBLIC_API = [
    "prepare_differentiable_simulation",
    "DifferentiableResult",
    "DifferentiableMaterialResult",
    "ParameterizedVertexDesign",
    "ObjectiveLossResult",
    "make_von_mises_loss",
    "make_stress_norm_loss",
    "make_optimizer",
    "OptimizationKind",
    "OptimizationProblem",
    "OptimizationRunResult",
    "prepare_optimization_problem",
    "prepare_parameterized_shape_problem",
    "run_optimization",
    "body_vertex_mask",
    "shape_gradient_for_body",
    "save_training_sample",
]

ADVANCED_COMPAT_API = [
    "solve_differentiable",
    "solve_differentiable_material_from_youngs",
    "build_solver_from_settings",
    "solver_body_ids_for_assembly",
    "solver_body_slot_mask",
    "solve_differentiable_material",
    "youngs_value_to_internal",
    "youngs_to_lame",
    "build_lame_from_youngs",
    "make_bounds_projector",
    "make_named_parameter_map",
    "make_parameter",
    "relative_scale",
    "scale_selected_vertices",
    "scale_selected_vertices_about_axis_center",
    "scale_selected_vertices_about_x_center",
    "selected_axis_center",
    "selected_x_center",
    "tan_half_angle_scale",
    "vertices_axis_le",
    "vertices_y_le",
    "create_polyfem_objective",
    "make_material_von_mises_loss",
    "material_design_vector",
    "SmoothTimeAggregationName",
    "TimeAggregation",
    "TimeAggregationName",
    "ScalarMaterialOptimizationProblem",
    "ScalarMaterialOptimizationStep",
    "apply_finite_difference_gradient_fallback",
    "collect_material_chain_diagnostics",
    "evaluate_material_loss_value_for_E",
    "finite_difference_material_E_gradient",
    "format_optional",
    "format_scalar_material_optimization_history_summary",
    "format_scalar_material_optimization_step",
    "make_material_optimizer",
    "objective_solution_rhs_diagnostics",
    "print_material_chain_diagnostics",
    "print_objective_rhs_diagnostics",
    "prepare_optimization_baseline_simulation",
    "prepare_material_differentiable_simulation",
    "prepare_material_optimization_problem",
    "prepare_scalar_youngs_material_problem",
    "report_optimization_baseline",
    "run_scalar_material_optimization",
    "usable_scalar_gradient",
    "ParameterizedShapeOptimizationProblem",
    "ShapeOptimizationProblem",
    "ShapeOptimizationStep",
    "format_shape_optimization_history_summary",
    "format_shape_optimization_step",
    "make_shape_optimizer",
    "make_von_mises_shape_loss",
    "prepare_parameterized_shape_differentiable_simulation",
    "prepare_parameterized_shape_optimization_problem",
    "prepare_shape_differentiable_simulation",
    "prepare_shape_optimization_problem",
    "print_shape_optimization_step",
    "run_shape_optimization",
    "get_direct_von_mises_monitor",
    "gradient_norm",
    "print_loss_summary",
    "print_parameterized_shape_summary",
    "print_scalar_material_summary",
]

ADVANCED_API = ADVANCED_COMPAT_API
COMPATIBILITY_API = ADVANCED_COMPAT_API

EXPORT_MODULES = {
    # Recommended public API.
    "prepare_differentiable_simulation": ".solve_diff",
    "DifferentiableResult": ".result_diff",
    "DifferentiableMaterialResult": ".result_diff",
    "ParameterizedVertexDesign": ".design",
    "ObjectiveLossResult": ".objective_bridge",
    "make_von_mises_loss": ".objective_bridge",
    "make_stress_norm_loss": ".objective_bridge",
    "make_optimizer": ".optimization_problem",
    "OptimizationKind": ".optimization_problem",
    "OptimizationProblem": ".optimization_problem",
    "OptimizationRunResult": ".optimization_problem",
    "prepare_optimization_baseline_simulation": ".optimization_problem",
    "prepare_optimization_problem": ".optimization_problem",
    "prepare_parameterized_shape_problem": ".shape_optimization",
    "report_optimization_baseline": ".optimization_problem",
    "run_optimization": ".optimization_problem",
    "body_vertex_mask": ".shape_mask",
    "shape_gradient_for_body": ".shape_mask",
    "save_training_sample": ".training_data",
    # Explicit compatibility / advanced imports. These stay available, but are
    # loaded lazily by ``polyfempy.differentiable`` so the top-level facade stays
    # small.
    "solve_differentiable": ".solve_diff",
    "solve_differentiable_material_from_youngs": ".solve_diff",
    "build_solver_from_settings": "._solve_settings",
    "solver_body_ids_for_assembly": ".solve_diff",
    "solver_body_slot_mask": ".solve_diff",
    "solve_differentiable_material": ".solve_diff",
    "youngs_value_to_internal": ".solve_diff",
    "youngs_to_lame": ".solve_diff",
    "build_lame_from_youngs": ".solve_diff",
    "make_bounds_projector": ".design",
    "make_named_parameter_map": ".design",
    "make_parameter": ".design",
    "relative_scale": ".geometry_maps",
    "scale_selected_vertices": ".geometry_maps",
    "scale_selected_vertices_about_axis_center": ".geometry_maps",
    "scale_selected_vertices_about_x_center": ".geometry_maps",
    "selected_axis_center": ".geometry_maps",
    "selected_x_center": ".geometry_maps",
    "tan_half_angle_scale": ".geometry_maps",
    "vertices_axis_le": ".geometry_maps",
    "vertices_y_le": ".geometry_maps",
    "create_polyfem_objective": ".objective_bridge",
    "make_material_von_mises_loss": ".objective_bridge",
    "material_design_vector": ".objective_bridge",
    "SmoothTimeAggregationName": ".objective_bridge",
    "TimeAggregation": ".objective_bridge",
    "TimeAggregationName": ".objective_bridge",
    "ScalarMaterialOptimizationProblem": ".material_optimization",
    "ScalarMaterialOptimizationStep": ".material_optimization",
    "format_scalar_material_optimization_history_summary": ".material_optimization",
    "format_scalar_material_optimization_step": ".material_optimization",
    "make_material_optimizer": ".material_optimization",
    "prepare_material_differentiable_simulation": ".material_optimization",
    "prepare_material_optimization_problem": ".material_optimization",
    "prepare_scalar_youngs_material_problem": ".material_optimization",
    "run_scalar_material_optimization": ".material_optimization",
    "ParameterizedShapeOptimizationProblem": ".shape_optimization",
    "ShapeOptimizationProblem": ".shape_optimization",
    "ShapeOptimizationStep": ".shape_optimization",
    "format_shape_optimization_history_summary": ".shape_optimization",
    "format_shape_optimization_step": ".shape_optimization",
    "make_shape_optimizer": ".shape_optimization",
    "make_von_mises_shape_loss": ".shape_optimization",
    "prepare_parameterized_shape_differentiable_simulation": ".shape_optimization",
    "prepare_parameterized_shape_optimization_problem": ".shape_optimization",
    "prepare_shape_differentiable_simulation": ".shape_optimization",
    "prepare_shape_optimization_problem": ".shape_optimization",
    "print_shape_optimization_step": ".shape_optimization",
    "run_shape_optimization": ".shape_optimization",
    "get_direct_von_mises_monitor": ".objective_bridge",
    "gradient_norm": ".summary",
    "print_loss_summary": ".summary",
    "print_parameterized_shape_summary": ".summary",
    "print_scalar_material_summary": ".summary",
    "apply_finite_difference_gradient_fallback": ".material_diagnostics",
    "collect_material_chain_diagnostics": ".material_diagnostics",
    "evaluate_material_loss_value_for_E": ".material_diagnostics",
    "finite_difference_material_E_gradient": ".material_diagnostics",
    "format_optional": ".material_diagnostics",
    "objective_solution_rhs_diagnostics": ".material_diagnostics",
    "print_material_chain_diagnostics": ".material_diagnostics",
    "print_objective_rhs_diagnostics": ".material_diagnostics",
    "usable_scalar_gradient": ".material_diagnostics",
}

__all__ = [
    "PUBLIC_API",
    "ADVANCED_COMPAT_API",
    "ADVANCED_API",
    "COMPATIBILITY_API",
    "EXPORT_MODULES",
]
