"""Generate explicit classic contact examples from polyfem-data JSON files."""

from __future__ import annotations

import copy
import keyword
from pathlib import Path
import re
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTACT_ROOT = ROOT / "polyfem-data" / "contact"
CONTACT_EXAMPLES = CONTACT_ROOT / "examples"
CONTACT_MESHES = CONTACT_ROOT / "meshes"
CLASSIC_EXAMPLES = ROOT / "examples" / "classic_example"
GENERATED_MARKER = "Generated by tools/generate_classic_contact_examples.py"

sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(CLASSIC_EXAMPLES))

from _contact_source_loader import load_contact_source_payload  # noqa: E402
from polyfempy.generated_api import generated_api as polyfem  # noqa: E402


TARGET_NAME_OVERRIDES = {
    "2D/golf-ball-doformable-wall.json": (
        "contact_2d_golf_ball_deformable_wall_generated_api.py"
    ),
    "3D/friction/high-school-physics-slopetest-mu=0.50.json": (
        "contact_3d_friction_high_school_slopetest_generated_api.py"
    ),
}

FACTORY_BY_CLASS = {}

BODY_ITEM_CLASSES = {
    "material": polyfem.Root.Materials,
    "velocity": polyfem.Root.Initial_conditions.Velocity.Item,
    "solution": polyfem.Root.Initial_conditions.Solution.Item,
    "acceleration": polyfem.Root.Initial_conditions.Acceleration.Item,
    "discr_order": polyfem.Root.Space.Discr_order.List.Item,
}

BOUNDARY_ITEM_CLASSES = {
    "dirichlet_boundary": (
        "dirichlet",
        polyfem.Root.Boundary_conditions.Dirichlet_boundary.Item,
    ),
    "neumann_boundary": (
        "neumann",
        polyfem.Root.Boundary_conditions.Neumann_boundary.Item,
    ),
    "normal_aligned_neumann_boundary": (
        "normal_aligned_neumann",
        polyfem.Root.Boundary_conditions.Normal_aligned_neumann_boundary.Item,
    ),
    "pressure_boundary": (
        "pressure",
        polyfem.Root.Boundary_conditions.Pressure_boundary.Item,
    ),
    "pressure_cavity": (
        "pressure_cavity",
        polyfem.Root.Boundary_conditions.Pressure_cavity.Item,
    ),
}

PREFERRED_FACTORY_NAMES = {
    polyfem.Root.Output.Data: "output_data",
    polyfem.Root.Output.Log: "output_log",
    polyfem.Root.Output.Paraview: "output_paraview",
    polyfem.Root.Output.Advanced: "output_advanced",
    polyfem.Root.Output.Reference: "output_reference",
}


def main() -> int:
    written = 0
    skipped = 0
    for source_json in source_jsons():
        target = target_path_for_source(source_json)
        if target.exists() and GENERATED_MARKER not in target.read_text(encoding="utf-8"):
            skipped += 1
            continue

        target.write_text(
            wrapper_text(source_json, target),
            encoding="utf-8",
            newline="\n",
        )
        written += 1

    print(
        f"Generated {written} classic contact example(s); "
        f"skipped {skipped} hand-written file(s)."
    )
    return 0


def source_jsons() -> list[Path]:
    paths: list[Path] = []
    for dim in ("2D", "3D"):
        for source_json in (CONTACT_EXAMPLES / dim).rglob("*.json"):
            if is_auxiliary_source(source_json):
                continue
            paths.append(source_json)
    return sorted(paths)


def is_auxiliary_source(source_json: Path) -> bool:
    return (
        source_json.name == "common.json"
        or source_json.name.endswith("-common.json")
        or source_json.name == "params.json"
    )


def target_path_for_source(source_json: Path) -> Path:
    dim = source_json.relative_to(CONTACT_EXAMPLES).parts[0]
    source_key = source_json.relative_to(CONTACT_EXAMPLES).as_posix()
    override = TARGET_NAME_OVERRIDES.get(source_key)
    if override is not None:
        return CLASSIC_EXAMPLES / dim / override

    relative_without_suffix = source_json.relative_to(CONTACT_EXAMPLES / dim).with_suffix("")
    slug = slugify("_".join(relative_without_suffix.parts))
    return CLASSIC_EXAMPLES / dim / f"contact_{dim.lower()}_{slug}_generated_api.py"


def slugify(value: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^0-9A-Za-z]+", "_", value)).strip("_").lower()


def wrapper_text(source_json: Path, target: Path) -> str:
    dim = source_json.relative_to(CONTACT_EXAMPLES).parts[0]
    common_module = "_contact_2d_common" if dim == "2D" else "_contact_3d_common"
    source_expr = path_expression(source_json.relative_to(CONTACT_EXAMPLES))
    source_label = source_json.relative_to(ROOT).as_posix()
    payload = load_contact_source_payload(source_json)
    try:
        polyfem.config(**copy.deepcopy(payload))
    except TypeError as exc:
        config_text = fallback_config_text(payload, str(exc))
        extra_import = "    SourcePayloadConfig,\n"
    else:
        builder_text = render_builder_config(payload)
        config_text = (
            builder_text
            if builder_text is not None
            else "polyfem_config = " + render_config(payload)
        )
        extra_import = ""

    return f'''#!/usr/bin/env python3
"""Classic {dim} contact example using generated_api.

Mirrors ``{source_label}``.
{GENERATED_MARKER}
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

EXAMPLE_DIR = Path(__file__).resolve().parent
if str(EXAMPLE_DIR) not in sys.path:
    sys.path.insert(0, str(EXAMPLE_DIR))

from {common_module} import (  # noqa: E402
    CONTACT_EXAMPLES_DIR,
    MESHES_DIR,
{extra_import}    config_for_workspace_from,
    polyfem,
    run_solve,
)


SOURCE_JSON = {source_expr}

{config_text}


def config_for_workspace(workspace: Path) -> Any:
    return config_for_workspace_from(polyfem_config, workspace)


def main() -> int:
    return run_solve(polyfem_config, "{target.stem}")


if __name__ == "__main__":
    raise SystemExit(main())
'''


def fallback_config_text(payload: dict[str, Any], reason: str) -> str:
    return (
        "# This source shape is not yet expressible by the generated API schema.\n"
        f"UNSUPPORTED_GENERATED_API_PAYLOAD = {render_literal(payload, 0)}\n\n"
        f"GENERATED_API_FALLBACK_REASON = {reason!r}\n"
        "polyfem_config = SourcePayloadConfig(\n"
        "    UNSUPPORTED_GENERATED_API_PAYLOAD,\n"
        "    source_json=SOURCE_JSON,\n"
        "    fallback_reason=GENERATED_API_FALLBACK_REASON,\n"
        ")"
    )


def render_builder_config(payload: dict[str, Any]) -> str | None:
    geometry = payload.get("geometry")
    if not isinstance(geometry, list):
        return None
    if any(not isinstance(item, dict) or item.get("type") != "mesh" for item in geometry):
        return None
    if any("volume_selection" not in item for item in geometry):
        return None

    materials = normalize_optional_items(payload.get("materials"))
    if any(not isinstance(item, dict) or "id" not in item for item in materials):
        return None

    volume_body_by_id: dict[int, str] = {}
    material_by_id = {item["id"]: item for item in materials}
    selection_handle_by_id: dict[int, str] = {}
    consumed_top_sections = {"geometry", "materials"}
    lines = ["model = polyfem.model()", ""]

    for index, material in enumerate(materials, start=1):
        material_id = material["id"]
        material_values = without_key(material, "id")
        lines.extend(
            assign_code(
                f"material_{index}",
                render_material_item(material_values, 0),
            )
        )
        material_by_id[material_id] = {
            "payload": material,
            "variable": f"material_{index}",
        }
    if materials:
        lines.append("")

    for index, item in enumerate(geometry, start=1):
        body_var = f"body_{index}"
        mesh_values = dict(item)
        mesh_values.pop("type", None)
        surface_selection = mesh_values.pop("surface_selection", None)
        point_selection = mesh_values.pop("point_selection", None)
        volume_id = mesh_values.get("volume_selection")
        if not isinstance(volume_id, int) or volume_id < 1:
            return None

        lines.extend(
            assign_code(
                body_var,
                render_method_call(
                    "model",
                    "mesh",
                    [],
                    render_kwargs(polyfem.Root.Geometry.Mesh, mesh_values, 4),
                    0,
                ),
            )
        )
        volume_body_by_id[volume_id] = body_var

        if volume_id in material_by_id:
            material_var = material_by_id[volume_id]["variable"]
            lines.extend(render_method_call(body_var, "material", [material_var], [], 0).splitlines())

        for selection_kind, selection_value in (
            ("surface", surface_selection),
            ("point", point_selection),
        ):
            selection_lines = render_selection_setup(
                body_var,
                selection_kind,
                selection_value,
                selection_handle_by_id,
            )
            if selection_lines is None:
                return None
            lines.extend(selection_lines)

        lines.append("")

    initial_lines, consumed_initial = render_initial_condition_bindings(
        payload.get("initial_conditions"),
        volume_body_by_id,
    )
    if initial_lines is None:
        return None
    consumed_top_sections.update(consumed_initial)
    lines.extend(initial_lines)

    space_lines, consumed_space = render_space_bindings(
        payload.get("space"),
        volume_body_by_id,
    )
    if space_lines is None:
        return None
    consumed_top_sections.update(consumed_space)
    lines.extend(space_lines)

    boundary_lines, config_rhs, consumed_boundary = render_boundary_bindings(
        payload.get("boundary_conditions"),
        selection_handle_by_id,
    )
    if boundary_lines is None:
        return None
    consumed_top_sections.update(consumed_boundary)
    lines.extend(boundary_lines)

    config_kwargs = []
    for key, value in payload.items():
        if key in consumed_top_sections:
            continue
        config_kwargs.append(
            (keyword_name(key), render_field_value(polyfem.Root, key, value, 4))
        )
    if config_rhs is not None:
        config_kwargs.append(("rhs", render_literal(config_rhs, 4)))

    lines.extend(
        assign_code(
            "polyfem_config",
            render_method_call("model", "config", [], config_kwargs, 0),
        )
    )
    return "\n".join(drop_repeated_blank_lines(lines))


def render_initial_condition_bindings(
    initial_conditions: Any,
    volume_body_by_id: dict[int, str],
) -> tuple[list[str] | None, set[str]]:
    if initial_conditions is None:
        return [], set()
    if not isinstance(initial_conditions, dict):
        return None, set()

    lines: list[str] = []
    for section, method in (
        ("velocity", "velocity"),
        ("solution", "solution"),
        ("acceleration", "acceleration"),
    ):
        items = normalize_optional_items(initial_conditions.get(section))
        for item in items:
            if not isinstance(item, dict) or item.get("id") not in volume_body_by_id:
                return None, set()
            body_var = volume_body_by_id[item["id"]]
            item_values = without_key(item, "id")
            lines.extend(
                render_method_call(
                    body_var,
                    method,
                    [
                        render_construct(
                            BODY_ITEM_CLASSES[method],
                            item_values,
                            4,
                        )
                    ],
                    [],
                    0,
                ).splitlines()
            )
    if lines:
        lines.append("")

    handled = {"velocity", "solution", "acceleration"}
    if any(key not in handled for key in initial_conditions):
        return None, set()
    return lines, {"initial_conditions"}


def render_space_bindings(
    space: Any,
    volume_body_by_id: dict[int, str],
) -> tuple[list[str] | None, set[str]]:
    if space is None:
        return [], set()
    if not isinstance(space, dict):
        return None, set()

    discr_order = space.get("discr_order")
    items = normalize_optional_items(discr_order)
    if not items or not all(isinstance(item, dict) for item in items):
        return [], set()
    if any(item.get("id") not in volume_body_by_id for item in items):
        return None, set()
    if any(key != "discr_order" for key in space):
        return None, set()

    lines: list[str] = []
    for item in items:
        body_var = volume_body_by_id[item["id"]]
        item_values = without_key(item, "id")
        lines.extend(
            render_method_call(
                body_var,
                "discr_order",
                [],
                render_kwargs(BODY_ITEM_CLASSES["discr_order"], item_values, 4),
                0,
            ).splitlines()
        )
    if lines:
        lines.append("")
    return lines, {"space"}


def render_boundary_bindings(
    boundary_conditions: Any,
    selection_handle_by_id: dict[int, str],
) -> tuple[list[str] | None, Any, set[str]]:
    if boundary_conditions is None:
        return [], None, set()
    if not isinstance(boundary_conditions, dict):
        return None, None, set()

    lines: list[str] = []
    rhs = boundary_conditions.get("rhs")
    for section, (method, item_cls) in BOUNDARY_ITEM_CLASSES.items():
        items = normalize_optional_items(boundary_conditions.get(section))
        for item in items:
            if not isinstance(item, dict) or item.get("id") not in selection_handle_by_id:
                return None, None, set()
            selection_var = selection_handle_by_id[item["id"]]
            item_values = without_key(item, "id")
            lines.extend(
                render_method_call(
                    selection_var,
                    method,
                    [],
                    render_kwargs(item_cls, item_values, 4),
                    0,
                ).splitlines()
            )

    handled = {"rhs", *BOUNDARY_ITEM_CLASSES}
    if any(key not in handled for key in boundary_conditions):
        return None, None, set()
    if lines:
        lines.append("")
    return lines, rhs, {"boundary_conditions"}


def render_selection_setup(
    body_var: str,
    selection_kind: str,
    selection_value: Any,
    selection_handle_by_id: dict[int, str],
) -> list[str] | None:
    if selection_value is None:
        return []
    if isinstance(selection_value, int):
        if selection_value <= 0:
            return []
        handle_var = f"{body_var}_{selection_kind}_{selection_value}"
        method = "surface_all" if selection_kind == "surface" else None
        if method is None:
            return None
        selection_handle_by_id.setdefault(selection_value, handle_var)
        return assign_code(
            handle_var,
            render_method_call(
                body_var,
                method,
                [],
                [("id", render_literal(selection_value, 4))],
                0,
            ),
        )

    if isinstance(selection_value, dict):
        return None

    items = selection_value if isinstance(selection_value, list) else [selection_value]
    lines: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            return None
        selection_id = item.get("id")
        if not isinstance(selection_id, int) or selection_id <= 0:
            return None
        method = selection_helper_method(selection_kind, item)
        if method is None:
            return None
        handle_var = f"{body_var}_{selection_kind}_{selection_id}"
        selection_handle_by_id.setdefault(selection_id, handle_var)
        lines.extend(
            assign_code(
                handle_var,
                render_method_call(
                    body_var,
                    method,
                    [],
                    [(keyword_name(key), render_literal(value, 4)) for key, value in item.items()],
                    0,
                ),
            )
        )
    return lines


def selection_helper_method(selection_kind: str, item: dict[str, Any]) -> str | None:
    helper_keys = [
        key
        for key in ("axis", "box", "sphere", "cylinder", "plane")
        if key in item
    ]
    if len(helper_keys) != 1:
        return None
    return f"{selection_kind}_{helper_keys[0]}"


def render_material_item(material: dict[str, Any], indent: int) -> str:
    variant = polyfem._select_variant(
        material,
        polyfem._LIST_VARIANTS[polyfem.Root.Materials],
    )
    return render_construct(variant, material, indent)


def render_kwargs(
    cls: type,
    values: dict[str, Any],
    value_indent: int,
) -> list[tuple[str, str]]:
    return [
        (
            keyword_name(polyfem._FIELD_ALIASES.get(cls, {}).get(key, key)),
            render_field_value(
                cls,
                polyfem._FIELD_ALIASES.get(cls, {}).get(key, key),
                value,
                value_indent,
            ),
        )
        for key, value in values.items()
    ]


def normalize_optional_items(value: Any) -> list[Any]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def without_key(value: dict[str, Any], key: str) -> dict[str, Any]:
    result = dict(value)
    result.pop(key, None)
    return result


def assign_code(variable: str, expression: str) -> list[str]:
    lines = expression.splitlines()
    lines[0] = f"{variable} = {lines[0]}"
    return lines


def drop_repeated_blank_lines(lines: list[str]) -> list[str]:
    result: list[str] = []
    previous_blank = False
    for line in lines:
        is_blank = line == ""
        if is_blank and previous_blank:
            continue
        result.append(line)
        previous_blank = is_blank
    return result


def render_config(payload: dict[str, Any]) -> str:
    return render_call(
        "config",
        [],
        [
            (keyword_name(key), render_field_value(polyfem.Root, key, value, 4))
            for key, value in payload.items()
        ],
        0,
    )


def render_field_value(parent_cls: type, key: str, value: Any, indent: int) -> str:
    canonical_key = polyfem._FIELD_ALIASES.get(parent_cls, {}).get(key, key)
    if canonical_key == "value" and not isinstance(value, dict):
        return render_literal(value, indent)

    wrapper_info = polyfem._FIELD_WRAPPERS.get(parent_cls, {}).get(canonical_key)
    if wrapper_info is None:
        return render_literal(value, indent)

    kind, wrapper = wrapper_info
    return render_wrapped_value(value, kind, wrapper, indent)


def render_wrapped_value(value: Any, kind: str, wrapper: type, indent: int) -> str:
    if value is None:
        return render_literal(value, indent)

    if kind == "object" and isinstance(value, dict):
        return render_construct(wrapper, value, indent)

    if kind == "list":
        items = value if isinstance(value, list) else [value]
        rendered_items = [
            render_list_item(wrapper, item, indent + 8)
            for item in items
        ]
        factory = factory_name(wrapper, required=False)
        if factory is None:
            return render_code_list(rendered_items, indent)
        return render_call(
            factory,
            [],
            [("items", render_code_list(rendered_items, indent + 4))],
            indent,
        )

    if kind == "polymorphic":
        if isinstance(value, dict):
            variant = polyfem._select_variant(
                value,
                polyfem._POLYMORPHIC_VARIANTS[wrapper],
            )
            inner = render_construct(variant, value, indent + 4)
            return render_call(factory_name(wrapper), [inner], [], indent)
        return render_literal(value, indent)

    return render_literal(value, indent)


def render_list_item(wrapper: type, item: Any, indent: int) -> str:
    variants = polyfem._LIST_VARIANTS.get(wrapper, ())
    if isinstance(item, dict):
        variant = polyfem._select_variant(item, variants)
        return render_construct(variant, item, indent)

    if len(variants) == 1 and not variants[0][2]:
        variant = variants[0][0]
        return render_call(
            factory_name(variant),
            [render_literal(item, indent + 4)],
            [],
            indent,
        )

    return render_literal(item, indent)


def render_construct(cls: type, values: dict[str, Any], indent: int) -> str:
    factory = factory_name(cls, required=False)
    if factory is None:
        return render_dict_literal(values, indent)

    auto_type = polyfem._CLASS_TYPE_NAMES.get(cls)
    non_type_keys = [key for key in values if key != "type"]
    kwargs = []
    for key, value in values.items():
        if key == "type" and value == auto_type and non_type_keys:
            continue
        canonical_key = polyfem._FIELD_ALIASES.get(cls, {}).get(key, key)
        kwargs.append(
            (
                keyword_name(canonical_key),
                render_field_value(cls, canonical_key, value, indent + 4),
            )
        )
    return render_call(factory, [], kwargs, indent)


def render_call(
    factory: str,
    args: list[str],
    kwargs: list[tuple[str, str]],
    indent: int,
) -> str:
    return render_callable_call(f"polyfem.{factory}", args, kwargs, indent)


def render_method_call(
    receiver: str,
    method: str,
    args: list[str],
    kwargs: list[tuple[str, str]],
    indent: int,
) -> str:
    return render_callable_call(f"{receiver}.{method}", args, kwargs, indent)


def render_callable_call(
    callee: str,
    args: list[str],
    kwargs: list[tuple[str, str]],
    indent: int,
) -> str:
    spaces = " " * indent
    child_spaces = " " * (indent + 4)
    if len(args) == 1 and not kwargs and "\n" not in args[0]:
        return f"{spaces}{callee}({args[0].strip()})"
    if not args and not kwargs:
        return f"{spaces}{callee}()"

    lines = [f"{spaces}{callee}("]
    for arg in args:
        arg_lines = arg.splitlines()
        if arg_lines:
            first = arg_lines[0]
            if first.startswith(child_spaces):
                arg_lines[0] = first
            else:
                arg_lines[0] = f"{child_spaces}{first.lstrip()}"
        lines.extend(arg_lines)
        lines[-1] += ","
    for key, value in kwargs:
        value_lines = value.splitlines()
        first = value_lines[0]
        if first.startswith(child_spaces):
            first = first[len(child_spaces):]
        else:
            first = first.lstrip()
        lines.append(f"{child_spaces}{key}={first}")
        lines.extend(value_lines[1:])
        lines[-1] += ","
    lines.append(f"{spaces})")
    return "\n".join(lines)


def render_literal(value: Any, indent: int) -> str:
    spaces = " " * indent
    simple = simple_literal(value)
    if simple is not None:
        return f"{spaces}{simple}"

    if isinstance(value, list):
        return render_list_literal(value, indent)
    if isinstance(value, dict):
        return render_dict_literal(value, indent)
    return f"{spaces}{value!r}"


def simple_literal(value: Any) -> str | None:
    if isinstance(value, str):
        return data_string_expression(value)
    if value is None or isinstance(value, (bool, int, float)):
        return repr(value)
    if isinstance(value, list) and is_simple_list(value):
        return "[" + ", ".join(simple_literal(item) for item in value) + "]"
    return None


def is_simple_list(value: list[Any]) -> bool:
    if not value:
        return True
    rendered = [simple_literal(item) for item in value]
    return None not in rendered and sum(len(item) for item in rendered) <= 80


def render_list_literal(value: list[Any], indent: int) -> str:
    spaces = " " * indent
    if not value:
        return f"{spaces}[]"

    lines = [f"{spaces}["]
    for item in value:
        item_text = render_literal(item, indent + 4)
        lines.extend(item_text.splitlines())
        lines[-1] += ","
    lines.append(f"{spaces}]")
    return "\n".join(lines)


def render_code_list(items: list[str], indent: int) -> str:
    spaces = " " * indent
    if not items:
        return f"{spaces}[]"

    lines = [f"{spaces}["]
    for item in items:
        lines.extend(item.splitlines())
        lines[-1] += ","
    lines.append(f"{spaces}]")
    return "\n".join(lines)


def render_dict_literal(value: dict[str, Any], indent: int) -> str:
    spaces = " " * indent
    if not value:
        return f"{spaces}{{}}"

    lines = [f"{spaces}{{"]
    for key, item in value.items():
        item_text = render_literal(item, indent + 4)
        item_lines = item_text.splitlines()
        first = item_lines[0][indent + 4 :]
        lines.append(f"{' ' * (indent + 4)}{key!r}: {first}")
        lines.extend(item_lines[1:])
        lines[-1] += ","
    lines.append(f"{spaces}}}")
    return "\n".join(lines)


def data_string_expression(value: str) -> str:
    path = Path(value)
    if not path.is_absolute():
        return repr(value)

    for name, root in (
        ("MESHES_DIR", CONTACT_MESHES.resolve()),
        ("CONTACT_EXAMPLES_DIR", CONTACT_EXAMPLES.resolve()),
    ):
        try:
            relative = path.resolve().relative_to(root)
        except ValueError:
            continue
        return path_expression(relative, base=name, as_str=True)

    return repr(value)


def path_expression(
    relative_source: Path,
    *,
    base: str = "CONTACT_EXAMPLES_DIR",
    as_str: bool = False,
) -> str:
    expr = base
    for part in relative_source.parts:
        expr += f' / "{part}"'
    return f"str({expr})" if as_str else expr


def keyword_name(name: str) -> str:
    if keyword.iskeyword(name):
        return f"{name}_"
    if not name.isidentifier():
        raise ValueError(f"cannot render {name!r} as a Python keyword argument")
    return name


def factory_name(cls: type, *, required: bool = True) -> str | None:
    preferred = PREFERRED_FACTORY_NAMES.get(cls)
    if preferred is not None:
        return preferred

    if not FACTORY_BY_CLASS:
        FACTORY_BY_CLASS.update(load_factory_map())
    try:
        return FACTORY_BY_CLASS[cls]
    except KeyError as exc:
        if not required:
            return None
        raise KeyError(f"no generated API factory found for {cls!r}") from exc


def load_factory_map() -> dict[type, str]:
    api_path = Path(polyfem.__file__).resolve()
    text = api_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"^def ([A-Za-z_]\w*)\(\*args, \*\*kwargs\):\n"
        r"    return _construct\((Root(?:\.[A-Za-z_]\w*)+), \*args, \*\*kwargs\)",
        re.MULTILINE,
    )
    factories: dict[type, str] = {}
    for name, class_expr in pattern.findall(text):
        cls = eval(class_expr, {"Root": polyfem.Root})
        factories.setdefault(cls, name)
    return factories


if __name__ == "__main__":
    raise SystemExit(main())
