set(SOURCES
  binding.cpp
  # bindings.cpp - kept as backup, but binding.cpp already defines PY_MODULE
)

source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX "Source Files" FILES ${SOURCES})
target_sources(polyfempy PRIVATE ${SOURCES})

################################################################################
# Subfolders
################################################################################

add_subdirectory(mesh)
add_subdirectory(state)
